spring.application.name=pedidos

spring.datasource.url=jdbc:postgresql://localhost:5433/pedidos
spring.datasource.username=docker
spring.datasource.password=docker
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.addresses=amqps://voowobdz:oPXu8xSnc3nXS_GlD6QR2wg9nz1afCdY@jackal.rmq.cloudamqp.com/voowobdz
spring.rabbitmq.port=5672

server.port=8090

eureka.client.enabled=false

