spring.application.name=pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/pedido
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.rabbitmq.host=jackal.rmq.cloudamqp.com
spring.rabbitmq.port=1883
spring.rabbitmq.username=voowobdz:voowobdz
spring.rabbitmq.password=oPXu8xSnc3nXS_GlD6QR2wg9nz1afCdY

server.port=8090

eureka.client.enabled=false

